server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
#    mybatisplus 测试需要配置jdbc数据源
#    driver-class-name: ${sky.datasource.driver-class-name}
#    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: ${sky.datasource.username}
#    password: ${sky.datasource.password}
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
#    hikari:
#      minimum-idle: 10
#      idle-timeout: 30000
#      maximum-pool-size: 20
#      max-lifetime: 120000
#      connection-timeout: 30000

  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.sky.entity
#  configuration:
#    #开启驼峰命名
#    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/com/sky/mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
#    admin-ttl: 720000
    admin-ttl: 99999999999999 #开发环境设置久点
    # 设置前端传递过来的令牌名称
    admin-token-name: token

#  微信登录，用户使用的配置
      # 设置jwt签名加密时使用的秘钥
    user-secret-key: itheima
    # 设置jwt过期时间
    #    admin-ttl: 720000
    user-ttl: 99999999999999 #开发环境设置久点
    # 设置前端传递过来的令牌名称
    user-token-name: authentication

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${access-key-id}
    access-key-secret: ${access-key-secret}
    bucket-name: ${bucket-name}

  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

